### ISSUE TITLE
Highlighting a full word is dropping spaces

### ISSUE THREAD

**Issue by kgrammer** [knownasilya/jquery-highlight#15]
When I highlight a full word or any part of a word that has a leading or trailing space, the space(s) are dropped.

For example, if I have a text that is "This is a test text string" and I search for "test", the word test is highlight, but the string is built so that it is displayed as "This is atesttext string" with "test" highlighted.

The HTML is built like:
    this is a 
        <span class="highlight">test</span>
    text string

So when rendered, the spaces before and after "test" are lost.

Is there a fix for this?

**Comment by knownasilya** [comment]
That is purely a style issue. Maybe give something like this a try

```css
.highlight {
  background-color: #FFF2B4;
  border-radius: 2px;
  padding: 0 1px;
}
```
